compras_productos_unidades:
    path:     /
    defaults: { _controller: "AppBundle:compras/ComprasProductosUnidades:index" }

compras_productos_unidades_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:compras/ComprasProductosUnidades:show" }

compras_productos_unidades_new:
    path:     /new
    defaults: { _controller: "AppBundle:compras/ComprasProductosUnidades:new" }

compras_productos_unidades_create:
    path:     /create
    defaults: { _controller: "AppBundle:compras/ComprasProductosUnidades:create" }
    requirements: { _method: post }

compras_productos_unidades_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:compras/ComprasProductosUnidades:edit" }

compras_productos_unidades_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:compras/ComprasProductosUnidades:update" }
    requirements: { _method: post|put }

compras_productos_unidades_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:compras/ComprasProductosUnidades:delete" }
    requirements: { _method: post|delete }
