compras_ingreso__seleccionar_sucursal:
    path:     /
    defaults: { _controller: "AppBundle:compras/ComprasIngreso:seleccionarSucursal" }

compras_ingreso__seleccionar_productos:
    path:     /{sucursal}/productos
    defaults: { _controller: "AppBundle:compras/ComprasIngreso:seleccionarProductos" }
