sucursales:
    path:     /
    defaults: { _controller: "AppBundle:Sucursales:index" }

sucursales_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Sucursales:show" }

sucursales_new:
    path:     /new
    defaults: { _controller: "AppBundle:Sucursales:new" }

sucursales_create:
    path:     /create
    defaults: { _controller: "AppBundle:Sucursales:create" }
    requirements: { _method: post }

sucursales_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Sucursales:edit" }

sucursales_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Sucursales:update" }
    requirements: { _method: post|put }

sucursales_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Sucursales:delete" }
    requirements: { _method: post|delete }
