app_sucursales_quejas:
    resource: "@AppBundle/Resources/config/routing/sucursalesquejas.yml"
    prefix:   /sucursales/quejas

homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    
app_sucursales_ventas:
    path:     /sucursales/ventas
    defaults: { _controller: "AppBundle:sucursales/Ventas:index" }

app_ws_sucursales_totales:
    path:     /ws/finanzas/sucursales/totales/{fecha}
    defaults: { _controller: "AppBundle:sucursales/Ventas:totales", fecha: '' }


############## RESOURCES ############## 
app_compras_pagos_formas:
    resource: "@AppBundle/Resources/config/routing/compraspagosformas.yml"
    prefix:   /compras/pagos/formas

app_compras_reportar:
    resource: "@AppBundle/Resources/config/routing/comprasreportar.yml"
    prefix:   /compras/reportar

app_empleados:
    resource: "@AppBundle/Resources/config/routing/empleados.yml"
    prefix:   /empleados

app_compras_productos:
    resource: "@AppBundle/Resources/config/routing/comprasproductos.yml"
    prefix:   /compras/productos

app_compras_ingreso:
    resource: "@AppBundle/Resources/config/routing/comprasingreso.yml"
    prefix:   /compras/ingreso
    
app_compras_ordenes:
    resource: "@AppBundle/Resources/config/routing/comprasordenes.yml"
    prefix:   /compras/ordenes
    
app_sucursales:
    resource: "@AppBundle/Resources/config/routing/sucursales.yml"
    prefix:   /sucursales

app_compras_productos_unidades:
    resource: "@AppBundle/Resources/config/routing/comprasproductosunidades.yml"
    prefix:   /compras/productos/unidades

app_compras_proveedores:
    resource: "@AppBundle/Resources/config/routing/comprasproveedores.yml"
    prefix:   /compras/proveedores