app_sucursales:
    resource: "@AppBundle/Resources/config/routing/sucursales.yml"
    prefix:   /sucursales

app_compras_productos_unidades:
    resource: "@AppBundle/Resources/config/routing/comprasproductosunidades.yml"
    prefix:   /compras/productos/unidades

app_compras_proveedores:
    resource: "@AppBundle/Resources/config/routing/comprasproveedores.yml"
    prefix:   /compras/proveedores

homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }

app_compras_productos:
    resource: "@AppBundle/Resources/config/routing/comprasproductos.yml"
    prefix:   /compras/productos

app_compras_ingreso:
    resource: "@AppBundle/Resources/config/routing/comprasingreso.yml"
    prefix:   /compras/ingreso

