AppBundle\Entity\ComprasOrdenesProductos:
    type: entity
    table: compras_ordenes_productos
    indexes:
        FK_producto:
            columns:
                - producto_id
        FK_cop_unidad:
            columns:
                - unidad_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cantidad:
            type: decimal
            nullable: false
            precision: 8
            scale: 2
            comment: ''
    manyToOne:
        unidad:
            targetEntity: ComprasProductosUnidades
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                unidad_id:
                    referencedColumnName: id
            orphanRemoval: false
        producto:
            targetEntity: ComprasProductos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                producto_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
