AppBundle\Entity\ComprasProductosUnidades:
    type: entity
    table: compras_productos_unidades
    indexes:
        activo:
            columns:
                - activo
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        abreviatura:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        nombreSingular:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: nombre_singular
        nombrePlural:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: nombre_plural
        activo:
            type: boolean
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
