AppBundle\Entity\ComprasOpciones:
    type: entity
    table: compras_opciones
    indexes:
        idx_clave:
            columns:
                - clave
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        clave:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        valor:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
