AppBundle\Entity\ComprasProveedores:
    type: entity
    table: compras_proveedores
    indexes:
        activo:
            columns:
                - activo
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        contacto:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        telefono:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        direccion:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        comentarios:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        activo:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
    lifecycleCallbacks: {  }
