AppBundle\Entity\ComprasOrdenes:
    type: entity
    table: compras_ordenes
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ingresadoDt:
            type: datetime
            nullable: false
            column: ingresado_dt
            
    manyToOne:
        creadoPor:
            targetEntity: Empleados
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                creado_por_id:
                    referencedColumnName: id
            orphanRemoval: false
        sucursal:
            targetEntity: Sucursales
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sucursal_id:
                    referencedColumnName: id
            orphanRemoval: false
        estado:
            targetEntity: ComprasOrdenesEstados
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                estado_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
