AppBundle\Entity\ComprasProductos:
    type: entity
    table: compras_productos
    indexes:
        FK_unidad:
            columns:
                - unidad_id
        FK_proveedor:
            columns:
                - proveedor_id
        activo:
            columns:
                - activo
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        descripcion:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        activo:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
        creadoDt:
            type: datetime
            nullable: false
            comment: ''
            column: creado_dt
        actualizadoDt:
            type: datetime
            nullable: false
            comment: ''
            column: actualizado_dt
    manyToOne:
        proveedor:
            targetEntity: ComprasProveedores
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                proveedor_id:
                    referencedColumnName: id
            orphanRemoval: false
        unidad:
            targetEntity: ComprasProductosUnidades
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                unidad_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
         prePersist: [setCreatedValue,setUpdatedValue]
         preUpdate: [setUpdatedValue]
