AppBundle\Entity\Cortez:
    type: entity
    table: cortez
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fecha:
            type: datetime
        total:
            type: decimal
        totalPendiente:
            type: decimal
            column: total_pendiente
        totalPosible:
            type: decimal
            column: total_posible
        totalAnulado:
            type: decimal
            column: total_anulado
        totalCancelado:
            type: decimal
            column: total_cancelado
        totalDescuentos:
            type: decimal
            column: total_descuentos
        totalCompras:
            type: decimal
            column: total_compras
        totalCuadrar:
            type: decimal
            column: total_cuadrar
        totalComprasCuadrar:
            type: decimal
            column: total_compras_cuadrar
    
    manyToOne:
        sucursal:
            targetEntity: Sucursales

    lifecycleCallbacks: {  }
