AppBundle\Entity\Empleados:
    type: entity
    table: empleados
    indexes:
        clave:
            columns:
                - clave
        activo:
            columns:
                - activo
        FK_supervisor:
            columns:
                - supervisor_id
    uniqueConstraints:
        usuario:
            columns:
                - usuario
        email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        usuario:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        clave:
            type: string
            nullable: false
            length: 40
            fixed: true
            comment: ''
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        activo:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
    manyToOne:
        supervisor:
            targetEntity: Empleados
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                supervisor_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
