AppBundle\Entity\EmpleadosRoles:
    type: entity
    table: empleados_roles
    indexes:
        FK_er_usuario:
            columns:
                - usuario_id
        FK_er_rol:
            columns:
                - rol_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        activo:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
    manyToOne:
        rol:
            targetEntity: Roles
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Empleados
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
