AppBundle\Entity\Roles:
    type: entity
    table: roles
    indexes:
        activo:
            columns:
                - activo
        nombre:
            columns:
                - nombre
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        descripcion:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        activo:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
    manyToMany:
        empleados:
          targetEntity: Empleados
          mappedBy: roles
          
    lifecycleCallbacks: {  }
